config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  get 'home/about' => "home/about"
  root to: 'posts#index'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  resources :tags, only: [:show]
  resources :users, only: [:show, :edit, :update, :destroy]
  resources :posts do
    resource :favorites, only: [:create, :destroy]
    resources :comments, only: [:create]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/install.rb
class Install < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :favorites
  has_many :post_tags
  has_many :tags, through: :post_tags
  has_many :users, through: :favorites

  def favorited_by?(user)
  	favorites.where(user_id: user.id).exists?
  end
end

app/models/post_tag.rb
class PostTag < ApplicationRecord
  belongs_to :tag
  belongs_to :post
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :post_tags
  has_many :posts, through: :post_tags
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable
  has_many :posts
  has_many :favorites
  # has_many :favorite_posts, through: :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.name
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20] # ランダムなパスワードを作成
      user.image = auth.info.image.gsub("_normal","") if user.provider == "twitter"
      user.image = auth.info.image.gsub("picture","picture?type=large") if user.provider == "facebook"
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
  	post = Post.find(params[:post_id])
  	comment = post.comments.new(comment_params)
  	comment.user_id = current_user.id
  	comment.save
  	redirect_to post_path(post.id)
  end

  def destroy
  end

  private
  def comment_params
  	params.require(:comment).permit(:body)
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
  	post = Post.find(params[:post_id])
  	favorite = current_user.favorites.new(post_id: post.id)
  	favorite.save
  	redirect_to posts_path
  end

  def destroy
  	post = Post.find(params[:post_id])
  	favorite = current_user.favorites.find_by(post_id: post.id)
  	favorite.destroy
  	redirect_to posts_path
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def about
	end
end

app/controllers/post_tag_controller.rb
class PostTagController < ApplicationController
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.page(params[:page]).reverse_order
    @search = @posts.ransack(params[:q])
    if params[:q].present?
      @posts = @search.result
      # Tag.find(PostTag.find_by(post_id: 54).tag_id).name  post_idからposttagsを検索して、そこから関連づいているtagのnameを取得している。
      # ランキング表示のための記述
    end
    @all_ranks = Post.find(Favorite.group(:post_id).order('count(post_id) desc').limit(3).pluck(:post_id))
  end

  def create
    post = Post.new(title: post_params[:title], body: post_params[:body])
    post.user_id = current_user.id
    if post.save
      unless params[:post][:tags].present?
        return redirect_to posts_path
      end
      params[:post][:tags].each do |tag|
        post_tag = PostTag.new
        post_tag.post_id = post.id
        post_tag.tag_id = tag.to_i
        if post_tag.save!
        end
      end
      redirect_to posts_path
    end
  end

  def show
  	@post = Post.find(params[:id])
    @comment = Comment.new
    @comments = @post.comments
    @tag = @post.tags
  end

  def new
    @post = Post.new
    @tags = Tag.all
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    post = Post.find(params[:id])
    post.update(post_params)
    redirect_to post_path(post.id)
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy
    flash[:notice] = "本当に削除しますか？"
    redirect_to user_path(current_user.id)
  end

  private
    def post_params
      params.require(:post).permit(:title, :body, tags: [])
    end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

	def show
	  @tag = Tag.find(params[:id])
	  # tagを起点にそのタグに関連づいているpostを探している
	  @tag_posts = @tag.posts
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
  	@user = User.find(params[:id])
  	@posts = @user.posts
  end

  def edit
  	@user = User.find(params[:id])
  end

  def update
  	user = User.find(params[:id])
  	user.update(user_params)
  	redirect_to user_path(user.id)
  end

  private
  def user_params
  	params.require(:user).permit(:name, :introduction)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/post_tag_helper.rb
module PostTagHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/posts/edit.html.erb
<h2>編集ページ</h2>

<%= form_for @post do |f| %>
  <p>title</p>
  <%= f.text_field :title %>
  <p>body</p>
  <%= f.text_area :body %>
  <%= f.submit "編集完了" %>
<% end %>

app/views/posts/index.html.erb
<h1 class="index-title">投稿一覧</h1>

<div class="index-ranking">
  いいね数の多い投稿はこちら！→
<!-- <%= Favorite.group(:post_id).order('count(post_id) desc').limit(3).pluck(:post_id) %> -->
<% @all_ranks.each.with_index(1) do |post, i| %>
  第
  <%= i %>
  位

  <span class="index-ranking-contents">
    <%= link_to post.title, post_path(post.id) %>
    <span>(<%= post.favorites.count %>いいね)</span>
  </span>
  <% end %>
</div>


<div class="index-contents">
    <% @posts.each do |post| %>
    <div class="index-content">
      <h2><%= link_to post.title, post_path(post.id) %></h2>
      <!-- ポスト→ポストタグで探索して、タグを探し出す。複数あるので、each文で取り出す。-->
      <span>タグ：</span>
      <% post.post_tags.each do |ptag| %>
      <span><%= link_to ptag.tag.name, tag_path(ptag.tag.id) %></span>
      <% end %><br/>
      <span class="index-contents-user" >by<%= link_to post.user.name, user_path(post.user.id) %></span>
      <span class="index-contents-date">作成日時<%= post.created_at %>更新日時<%= post.updated_at %></span>

      <span class="index-contents-comments"><%= post.comments.count %>コメント</span>

      <span class="index-contents-fav"><%= post.favorites.count %>いいね</span><br/>
    </div>
    <% end %>
  <%= paginate @posts %>
</div>

app/views/posts/new.html.erb
<%= form_with(model: @post) do |f| %>
  <%= f.label :title,"タイトル" %><br />
  <%= f.text_field :title %><br/>

  <%= f.label :body,"本文" %><br />
  <%= f.text_area :body %><br />

  <%= f.label :tags,"タグ" %><br />
  <%= f.collection_check_boxes :tags, @tags, :id, :name, include_hidden: false %><br/>

  <%= f.submit "作成" %>

<% end %>

app/views/posts/show.html.erb
  <div class="block-contents">
  <div class="block-head">
    <div class="block-date">
      <p><%= @post.created_at %><%= @post.updated_at %></p>
    </div>
    <div class="block-tags">
      <p class="tag"><投稿のタグ></p>
    </div>
    <div class="block-fav">
      <% if @post.favorited_by?(current_user) %>
        <li>
          <%= link_to post_favorites_path(@post), method: :delete do %>
            <i class="fa fa-heart" aria-hidden="true" style="color: red;"></i>
              <%= @post.favorites.count %><br/> いいねを取り消す
          <% end %>
        </li>
        <% else %>
          <li>
            <%= link_to post_favorites_path(@post), method: :post do %>
              <i class="fa fa-heart" aria-hidden="true"></i>
              <% if @post.favorites.count >= 1 %>
              <%= @post.favorites.count %><br/> いいねする
        <% else %>
          <p>いいねする</p>
        <% end %>
      <% end %>
          </li>
      <% end %>
    </div>
    <h1 class="block-title"><%= @post.title %></h1>
  <div class="block-user">
    <p>by：<%= link_to @post.user.name, user_path(@post.user) %></p>
  </div>
</div>

<div class="block-body">
  <p><%= @post.body %></p>
</div>

<div class="block-comments">
  <div class="block-comment-post">
    <%= form_for [@post, @comment] do |f| %>
      <%= f.text_area :body, placeholder: "コメントをここに" %>
      <%= f.submit "コメントを送信する" %>
    <% end %>
  </div>

  <div class="block-comment-index">
    <% @comments.each do |comment| %>
      <span class="comment-user-name"><%= comment.user.name %></span>
      <span class="date"><%= comment.created_at%><%= comment.updated_at%></span>
      <p class="comment-contents"><%= comment.body %></p>
    <% end %>
  </div>
</div>

<%= link_to "戻る", posts_path %>
</div>

app/views/tags/show.html.erb
<h1>タグ：<%= @tag.name %>の投稿一覧</h1>


<div class="index-contents">
    <% @tag_posts.each do |tag_post| %>
    <div class="index-content">
      <h2><%= link_to tag_post.title, post_path(tag_post.id) %></h2>
      <!-- タグに表示、each文で取り出す。-->
      <span>タグ：</span>
      <% tag_post.tags.each do |ptag| %>
      <span><%= link_to ptag.name, tag_path(ptag.id) %></span>
      <% end %><br/>
      <span class="index-contents-user" >by<%= link_to tag_post.user.name, user_path(tag_post.user.id) %></span>
      <span class="index-contents-date">作成日時<%= tag_post.created_at %>更新日時<%= tag_post.updated_at %></span>

      <span class="index-contents-comments"><%= tag_post.comments.count %>コメント</span>

      <span class="index-contents-fav"><%= tag_post.favorites.count %>いいね</span><br/>
    </div>
    <% end %>
</div>