config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  get 'home/about' => "home/about"
  root to: 'posts#index'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  resources :tags, only: [:show]
  resources :users, only: [:show, :edit, :update, :destroy]
  resources :posts do
    resource :favorites, only: [:create, :destroy]
    resources :comments, only: [:create]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/install.rb
class Install < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :favorites
  has_many :post_tags
  has_many :tags, through: :post_tags
  has_many :users, through: :favorites

  def favorited_by?(user)
  	favorites.where(user_id: user.id).exists?
  end
end

app/models/post_tag.rb
class PostTag < ApplicationRecord
  belongs_to :tag
  belongs_to :post
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :post_tags
  has_many :posts, through: :post_tags
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable
  has_many :posts
  has_many :favorites
  # has_many :favorite_posts, through: :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.name
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20] # ランダムなパスワードを作成
      user.image = auth.info.image.gsub("_normal","") if user.provider == "twitter"
      user.image = auth.info.image.gsub("picture","picture?type=large") if user.provider == "facebook"
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def about
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.page(params[:page]).reverse_order
    @search = @posts.ransack(params[:q])
    if params[:q].present?
      @posts = @search.result
      # Tag.find(PostTag.find_by(post_id: 54).tag_id).name  post_idからposttagsを検索して、そこから関連づいているtagのnameを取得している。
      # ランキング表示のための記述
    end
    @all_ranks = Post.find(Favorite.group(:post_id).order('count(post_id) desc').limit(3).pluck(:post_id))
  end

  def create
    post = Post.new(title: post_params[:title], body: post_params[:body])
    post.user_id = current_user.id
    if post.save
      unless params[:post][:tags].present?
        return redirect_to posts_path
      end
      params[:post][:tags].each do |tag|
        post_tag = PostTag.new
        post_tag.post_id = post.id
        post_tag.tag_id = tag.to_i
        if post_tag.save!
        end
      end
      redirect_to posts_path
    end
  end

  def show
  	@post = Post.find(params[:id])
    @comment = Comment.new
    @comments = @post.comments
    @tag = @post.tags
  end

  def new
    @post = Post.new
    @tags = Tag.all
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    post = Post.find(params[:id])
    post.update(post_params)
    redirect_to post_path(post.id)
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy
    flash[:notice] = "本当に削除しますか？"
    redirect_to user_path(current_user.id)
  end

  private
    def post_params
      params.require(:post).permit(:title, :body, tags: [])
    end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

	def show
	  @tag = Tag.find(params[:id])
	  # tagを起点にそのタグに関連づいているpostを探している
	  @tag_posts = @tag.posts
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
  	@user = User.find(params[:id])
  	@posts = @user.posts
  end

  def edit
  	@user = User.find(params[:id])
  end

  def update
  	user = User.find(params[:id])
  	user.update(user_params)
  	redirect_to user_path(user.id)
  end

  private
  def user_params
  	params.require(:user).permit(:name, :introduction)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/post_tag_helper.rb
module PostTagHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
    <header id="header", class="header">
      <!-- ログイン時のヘッダー -->
      <% if user_signed_in? %>
        <nav class="nav">
          <div class="container">
            <div class="nav-bar">
              <ul class="nav-items">
                <li>
                  <h1><%= link_to "MusicRounge", posts_path %></h1>
                </li>
                <li class="nav-item">
                  <%= link_to "about", home_about_path, class: "nav-link btn btn-primary" %>
                </li>
                <li class="nav-item">
                  <%= link_to "マイページ", user_path(current_user.id), class: "nav-link btn btn-primary" %>
                </li>
                <li class="nav-item">
                  <%= link_to "新規投稿", new_post_path, class: "nav-link btn btn-primary" %>
                </li>
                <li class="nav-item">
                  <%= link_to "ログアウト", destroy_user_session_path, class: "nav-link btn btn-primary" %>
                </li>
                <li class="nav-item">
                  <%= search_form_for @search do |f| %>
                    <%= f.search_field :title_or_body_cont %>
                    <%= f.submit "検索" %>
                  <% end %>
                </li>
              </ul>
            </div>
          </div>
        </nav>
        <!-- ログインしていない時のヘッダー-->
        <% else %>
          <nav class="nav">
          <div class="container">
            <div class="nav-bar">
              <ul class="nav-items">
                <li>
                  <h1><%= link_to "MusicRounge", posts_path %></h1>
                </li>
                <li class="nav-item">
                  <%= link_to "about", home_about_path, class: "nav-link btn btn-primary" %>
                </li>
                <li class="nav-item">
                  <%= link_to "新規登録", new_user_registration_path, class: "nav-link btn btn-primary" %>
                </li>
                <li class="nav-item">
                  <%= link_to "ログイン", new_user_session_path, class: "nav-link btn btn-primary" %>
                </li>
                <li class="nav-item">
                  <%= search_form_for @search do |f| %>
                    <%= f.search_field :title_or_body_cont %>
                    <%= f.submit "検索" %>
                  <% end %>
                </li>
              </ul>
            </div>
          </div>
        </nav>
      <% end %>
    </header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicRounge</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" rel="stylesheet">
  </head>

  <body>
  <%= render 'layouts/header' %>
    <%= yield %>

  </body>
</html>